# Generated by Django 3.1.4 on 2021-07-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(null=True, upload_to='flunky_images')),
                ('status', models.BooleanField(default=True)),
                ('avialable', models.BooleanField(default=True)),
                ('ip', models.CharField(max_length=15)),
                ('port', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bots',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_no', models.IntegerField()),
                ('bot_name', models.CharField(max_length=30)),
                ('table_no', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('food_delivered', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('avialable', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='table_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ('-table_number',),
            },
        ),
    ]
