# Generated by Django 3.1.4 on 2021-07-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlunkeyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='avialable',
            field=models.BooleanField(default=True, help_text='available or not avialabe for delivery'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='status',
            field=models.BooleanField(default=True, help_text='bot working(active or inactive)'),
        ),
    ]
