# Generated by Django 3.1.4 on 2021-07-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlunkeyApp', '0002_auto_20210728_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='image',
            field=models.ImageField(blank=True, upload_to='flunky_images'),
        ),
    ]
