# Generated by Django 3.1.4 on 2021-07-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlunkeyApp', '0005_auto_20210729_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_no', models.IntegerField()),
                ('bot_name', models.CharField(max_length=30)),
                ('table_no', models.IntegerField()),
                ('ip', models.CharField(max_length=20)),
                ('port', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('food_delivered', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'All Deliveries',
            },
        ),
    ]
